[tool.poetry]
name = "knowbe4-scripts"
version = "0.1.0"
description = ""
authors = ["Mike Babb <mike7400@gmail.com>"]
readme = "README.md"
packages = [{include = "knowbe4_scripts"}]

[tool.poetry.dependencies]
python = "^3.11"
gql = "^3.4.1"
requests-toolbelt = "^1.0.0"


[tool.poetry.group.dev.dependencies]
googleapiutils2 = "^0.6.0"
pandas = "^2.0.2"
requests = "^2.31.0"
mypy = "^1.3.0"
black = "^23.3.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
